apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:0.54
        ports: 
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef: 
              name: mongodb-secret
              key: mongo_root_username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongodb-secret
              key: mongo_root_password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef: 
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector: 
    app: mongo-express
  type: LoadBalancer  # an external service
  ports:
    - protocol: TCP
      port: 8081  #service port
      targetPort: 8081 #container port
      nodePort: 30000  #exposes the external service on this port


